### ISSUE TITLE
Json instead of libconfig?

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#1]
https://github.com/HotPocketDev/core/blob/f9e0a7ad479b62f296e45be49dd567e395766a15/src/keys.cpp#L5

We're going to be processing a lot of JSON from public users connected to hot pocket nodes.

Config files are basically JSON anyway. 

Let's consider using https://github.com/nlohmann/json for both to save on library overhead?

**Comment by ravinsp** [comment]
Thanks. I was going to look at protobuf to replace libconfig, but it looked like protobuf would not be first-choice for human-readable formats. I agree on going with json. Will start work on this.

**Comment by ravinsp** [comment]
Fixed in #2
