### ISSUE TITLE
Peer to peer base message structure

### ISSUE THREAD

**Issue by asanka-indrajith** [HotPocketDev/core#11]
As per initial design for peer-to-peer container message I have implemented following protobuf schema.
```
message Message {
  optional string version = 1;
  optional bytes publicKey = 2;
  optional int32 timestamp = 3;
  optional bytes signature = 4;

  enum Messagetype {
    PROPOSAL = 0;
    NPL = 1;
    STATE_REQUEST = 2;
    STATE_RESPONSE = 3;
    HISTORY_REQUEST = 4;
    HISTORY_RESPONSE = 5;
  }

  optional Messagetype type = 5;
  optional bytes content = 6;
}
```

Here content would be another serialized message of message type set in container message.
i.e: if message type is 'PROPSAL' then content would be serialized object of following message schema.
```
message Proposal {
  repeated string connections = 1;
  repeated string inputs = 2;
  repeated string outputs = 3;
  optional int32 stage = 4;
  optional int32 time = 5;
  optional State state = 6;
  optional bytes lcl = 7;
}
```
We've opted to use this approach rather than having all attributes in one message is to avoid having default values for unused fields which can make message size bigger.
ie: npl message having proposal related fields doesn't make any sense.

**Comment by ravinsp** [comment]
A thought regarding "version" field. Each incoming peer message version will have to be compared with the node's own HP version. Since comparing dot-separated versions (eg. "1.12.3") is not efficient I propose an integer based version number in protobuf messages.

**Comment by codetsunami** [comment]
Protocol version number should be completely separate to the project version number.

Protocol version number should only increase when the protocol is altered. Think for example HTTP 1.0, HTTP 1.1. You don't have a new HTTP version each time chrome releases an update.

And I agree the protocol number should be an integer.

I'm noticing in the Proposal message type you have repeated string for connections, inputs, outputs. This is probably incorrect as it implies there is further parsing to do after protobuf has finished decoding. The point of protobuf is to do all the encoding and decoding for you in an efficient way and with regard to the endianness of your machine. So we should not be encoding any data in a way that needs 'further decoding'

Proposal inputs and outputs share a common structure which changes depending on the stage of the consensus round. At stage 0 they are a mapping like so: { user_public_key => [ ... array of user's inputs ], ... }. At stages > 0 each is a simple array containing hashes of the mappings from stage 0: e.g. [ ... hash of each stage 0 mapping ]

Because the hash of that mapping will need to be computed efficiently over the serialised field you will need a message type that represents that mapping, and presumably another message type that allows the input/output field to be populated by either structure

**Comment by ravinsp** [comment]
Timestamp int32 --> uint64 (epoch milliseconds)
For example `std::chrono` timestamp is represented as `uint64_t`.

**Comment by asanka-indrajith** [comment]
@ravinsp :  protobuf 3.0 provide `Timestamp` message type. We can use that as well. It provides lot of helper methods to set time. Only concern is, it uses int64 types inside not uint64.
[https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto](url)

**Comment by asanka-indrajith** [comment]
Starting implementing peer message handling, I came to think of few changes we might need to do to the current message structure. 

1. We can get rid of additional content serialization by using protobuf `one of` type. So we can remove that extra serialization from current container.

2. But I've few concerns over message signing and validation. For the current approach, when signing message, First we have to serialize current message to a string/byte array (probably using protobuf) then pass it to the signing function with public key and get signature, put it again into message and then again serialize and send it. we'll need to follow a revers approach of similar complexity for message parsing as well.
 
But we can remove these additional work by moving signature to a upper level container such as;
```
message Container
{
 optional string version = 1;
 optional Message message= 2;
}

message Message {
  optional string version = 1;
  optional bytes publicKey = 2;
  optional int32 timestamp = 3;
  optional bytes signature = 4;

  enum Messagetype {
    PROPOSAL = 0;
    NPL = 1;
    STATE_REQUEST = 2;
    STATE_RESPONSE = 3;
    HISTORY_REQUEST = 4;
    HISTORY_RESPONSE = 5;
  }

  optional Messagetype type = 5;
  oneof content {
        Proposal  proposal = 1;
        NPL npl = 2;
    }
}
```
This way we'll avoid extra serialization and parsing rounds. What do you guys think?

**Comment by codetsunami** [comment]
RE: oneof
See: https://developers.google.com/protocol-buffers/docs/proto#oneof-features
```Backwards-compatibility issues
Be careful when adding or removing oneof fields. If checking the value of a oneof returns None/NOT_SET, it could mean that the oneof has not been set or it has been set to a field in a different version of the oneof. There is no way to tell the difference, since there's no way to know if an unknown field on the wire is a member of the oneof.```

I would suggest leaving it as a binary field is a better approach for forward compatibility. It's a very small amount of additional programmer overhead to run protobuf parser again on the binary field and we preserve forward compatibility.

**Comment by asanka-indrajith** [comment]
Thinking in the same line, I think we can improve performance by changing type of field ``message`` of Container message to binary as well.

**Comment by ravinsp** [comment]
Do we know the buffer parsing behavior of protobuf? We get the container message bytes from the socket and protobuf will parse it and assign the relevant portion of the bytes to the “Message” field as a std::string. Do we know the behavior of how it assigns the chunk of bytes to the string? Any copies involved? Might need to read the protobuf source files?

**Comment by codetsunami** [comment]
There's significant discussion about exposing string_view or equivalent in protobuf here: https://github.com/protocolbuffers/protobuf/issues/1896

I'm unclear what the outcome was.

Looking at what has been compiled by protobuf for our project:
You can use r-value setters:
https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/p2p/message.pb.h#L314

And you can use pre-allocated external strings
https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/p2p/message.pb.h#L379

And likewise once a string is returned from protobuf a string_view can be created from that and passed around as needed, provided the life of the string is managed correctly.

https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/p2p/message.pb.h#L2130

**Comment by codetsunami** [comment]
I think internally protobuf has a single copy of the string and fetching it won't produce a deep copy unless you ask for one

https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/p2p/message.pb.h#L2130-L2133

https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/p2p/message.pb.h#L2142-L2144

https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/p2p/message.pb.h#L421

https://github.com/protocolbuffers/protobuf/blob/d8e678aae4c77e32fe5e8e92046eb66f74dfd269/src/google/protobuf/arenastring.h#L286
```C++
  inline const ::std::string& GetNoArena() const { return *ptr_; }
```

https://github.com/protocolbuffers/protobuf/blob/d8e678aae4c77e32fe5e8e92046eb66f74dfd269/src/google/protobuf/arenastring.h#L275-L281
```C++
  void SetNoArena(const ::std::string* default_value, ::std::string&& value) {
    if (IsDefault(default_value)) {
      ptr_ = new ::std::string(std::move(value));
    } else {
      *ptr_ = std::move(value);
    }
  }
```

**Comment by ravinsp** [comment]
Cool! Thanks for you research. I’m also gonna read up on this when u get to a pc. Still, even with string pointer retrieval, we are going to have extra copies. The problem is additional container message and deserialization step required for signature verification. 
1. We have to deserialize the container message. Protobuf will copy the large byte portion for the ‘message’ field and small byte portion to the ‘signature’ fields to its internal string. (It would be ideal if this were copyless like string-view projection, but it looks like it’s not). 

2. Then we do signature verification (this can be done using the string pointers given by protobuf so no issue)

3. The we have deserialize the content message again to reveal the actual object. This will create its own copies of internal strings from the bytes that got deserialized. 

We will have to optimize the extra step for signature verification.

**Comment by ravinsp** [comment]
If nothing else works, one thing we could you with a good old fashioned byte chunk pattern without the help of protobuf for the initial step. Every message bytes will be prefixed with signature bytes (sig is fixed length). Then we do signature verification just using projection (no copies). 

We only hand over to protobuf deserialization after verifying the signature. I know this is a very primitive idea. It would also not protect us with protocol versioning as well.

**Comment by codetsunami** [comment]
Worth looking at https://capnproto.org/

**Comment by ravinsp** [comment]
A very good comparison on alternatives by capnproto author:
https://capnproto.org/news/2014-06-17-capnproto-flatbuffers-sbe.html

**Comment by ravinsp** [comment]
Protobuf vs capnproto vs flatbuffers vs SBE

My decision process:

1. Protobuf is out. P2P message processing is one of the core and high-scale activities of hot pocket and protobuf is not optimized enough for us.

2. SBE is out. One reason among several: Not flexible enough for future evolution of the protocol we might require. Quoted from capnproto author: “SBE, however, as far as I can tell from reading the code, does not allow you to add new variable-width fields inside of a sub-object. 

That leaves capnproto vs flatbuffers. I couldn’t find compelling differences between the two for our requirement. 

Considering security aspects of the two:

1. Capnproto is still at 0.X release stage (latest version 0.7 was released last year 2018).  Quote from security section of FAQ: “Cap’n Proto’s C++ reference implementation has not yet undergone a formal security review. It may have bugs.” Security report [cvedetails](https://www.cvedetails.com/vulnerability-list/vendor_id-16364/product_id-37224/Capnproto-Capnproto.html)

2. Flatbuffers is now at version 1.11. Seems they have 6month release cycle. Google-backed. Flatbuffers security considerations: https://github.com/dvidelabs/flatcc/blob/master/doc/security.md. Flatbuffers is also used by Facebook as well but although it’s operating within an already authenticated client. [blog post](https://engineering.fb.com/android/improving-facebook-s-performance-on-android-with-flatbuffers/)

**Comment by codetsunami** [comment]
I like your reasoning. I also think FlatBuffers might be the best option moving forward.

**Comment by ravinsp** [comment]
Assuming we are going forward with FlatBuffers, this may kickstart our work tomorrow:

1. [Using “Union”](https://stackoverflow.com/questions/37685003/flatbuffers-send-multiple-packet-types-using-a-union) for embedding multiple message types inside parent message. 

2. Using verify at the reader side to validate buffer offset overflows etc... (important for security in our use case)
`bool ok = VerifyMonsterBuffer(Verifier(buf, len));`

**Comment by asanka-indrajith** [comment]
Closing this issue. I have opened a separate issue to discuss schema implementation using FlatBuffer [here](https://github.com/HotPocketDev/core/issues/27).
