### ISSUE TITLE
Json schema validation

### ISSUE THREAD

**Issue by ravinsp** [HotPocketDev/core#14]
Currently we use RapidJson schema-based validation to ensure user challenge response structure. 

Would we be better off with performance if we only use RapidJson .HasMember() and .IsInt() kind of manual checks rather than using json schema validation?

We do the same (schema) validation for config file as well. But it would be ok since that is a one-off thing during startup.

**Comment by codetsunami** [comment]
I don't think schema validation offers much in the way of benefit for the challenge response structure, and the overhead of checking it might be expensive and therefore open potential DDoS attack surface area.

Handshake messages, especially public handshake messages, should always be processed as cheaply as possible, to the point that I would suggest avoiding the JSON parser for helo/challenge response and just draw out the response value with an inexpensive regex.

A 'billing' system needs to be added that can 'bill' (punish) users for incorrect or malformed requests and then selectively block them if they go over a certain threshold of resource usage per unit time.

**Comment by codetsunami** [comment]
And the same argument can be made for sending the challenge message. Resource cost is the main issue. If someone has 100,000 nodes all requesting challenges we don't want to be constructing a heavy JSON document for each of those when we could just return something that's little more than an sprintf

**Comment by codetsunami** [comment]
Obviously these design decisions should be documented in code so people don't ask why we're using the full JSON parser in some places and not others

**Comment by ravinsp** [comment]
OK. Another thing we can do is since we can estimate the max length of a challenge response, we monitor the read buffer for the initial message and drop the connection if it exceeds. For the user binary communication (contract inputs), we may need to enforce some hard limit like max input size.

As for the regex, I will keep RapidJson parser for now instead of regex validation. Doing several manual regex to validate various challenge response components might also be expensive and subject to loopholes. Instead I will get rid of Schema validator and also manually construct the challenge json string,

**Comment by codetsunami** [comment]
Dropping connections that send say 2x the expected size of the message is a good idea.

You might be right about C++ std::regex being expensive as well. Some benchmarking might be good.

In addition to dropping bad connections we should also drop incoming public connections when the process is congested. Ideally the HP instance should continue to run under a DDoS scenario because it will still have its protected peer connections even if it's dropping all new/incoming connections.

**Comment by ravinsp** [comment]
I've logged the following work items in our internal tracker.

75302 - Add message length monitoring for socket reads
75303 - Add connection rejection based on current load
75304 - Drop misbehaving connections (malformed messages)
75305 - Blacklist bad actors and reject new connections

**Comment by codetsunami** [comment]
Sounds good
