### ISSUE TITLE
C++ exceptions

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#19]
So far this project has been built around using return values / error codes rather than exceptions, much like a C project. I think this is a good approach for performance and is my preferred model personally.

We should consider setting the -fno-exceptions compiler flag in CMakeLists. I'm not sure if any of the libraries we currently depend on require / must use exceptions. If there are we should consider alternatives or possibly use of noexcept keyword

**Comment by ravinsp** [comment]
RapidJSON and Libsodium doesn't use exceptions. Beast seem to be using them. We use Boost filesystem and that also throws exceptions.

**Comment by codetsunami** [comment]
Beast is part of Boost and will follow their dual except/noeexcept design

All we need to do is specify the appropriate macro and provide an error handler.

See: https://www.boost.org/doc/libs/1_54_0/libs/exception/doc/throw_exception.html

**Comment by ravidulashan** [comment]
Got an issue when trying to compile using compiler flag `-fno-exceptions`
**/usr/local/include/boost/filesystem/operations.hpp: In constructor ‘boost::filesystem::filesystem_error::filesystem_error(const string&, boost::system::error_code)’:
/usr/local/include/boost/filesystem/operations.hpp:83:16: error: exception handling disabled, use -fexceptions to enable**

So kept it aside to investigate it. And moved on to other important areas

**Comment by codetsunami** [comment]
https://stackoverflow.com/questions/30131827/does-boost-no-exceptions-guarantee-compatibility-to-fno-exceptions

Issue discussed there. Probably just need to define BOOST_NO_EXCEPTIONS in conjunction with the compiler flag

**Comment by ravidulashan** [comment]
We tried defining BOOST_NO_EXCEPTIONS and also we saw the stackoverflow thread. But no luck resolving it.

**Comment by ravinsp** [comment]
This is probably because we are using boost::filesystem. I think we can replace that with std::filesystem. Let's revisit this when we finish off more important stuff.

**Comment by ravinsp** [comment]
Fixed in  0fb9ebf
Replaced `boost::filesystem` with `std::experimental::filesystem` (Didn't use `std::filesystem` because of requirement of requirement gcc-8 or newer.
