### ISSUE TITLE
shared_ptr overuse

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#22]
https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/sock/socket_session.cpp#L113

As discussed briefly with Ravin over email in many use-cases for this function there is no need to suffer the overhead of a shared_ptr. Mostly you want to generate a message once and send it to a single socket. In these cases an alternative should be used, namely ownership of the object should be transferred to the queue.

Watch a few minutes of this video from time 48m to learn about the significant overhead of shared_ptr. https://vimeo.com/131189627#t=2880s

In some cases (namely broadcast messages) you will need to reference count a message so we should overload rather than eliminate shared_ptr here.

Here's an example I've devised showing how you might manage a heterogeneous queue of smart pointers to strings, avoiding shared_ptr overhead where you can.

```C++
    // create the message queue
    deque<variant<unique_ptr<string>, shared_ptr<string>>> queue;
    
    // populate it with some different message types
    queue.push_back(make_unique<string>("abcdef"));
    queue.push_back(make_unique<string>("deadbeef"));
    queue.push_back(make_shared<string>("hi there"));

    // read and empty the queue to stdout
    while (!queue.empty()) {
        auto& x = queue.front();
        visit([](auto&& x){std::cout << *x << "\n";}, x);
        queue.pop_front();
    }
```

As an aside I'm not sure what's going on with the member names having a trailing underscores in this module. For consistency and aesthetics I think these should be removed.

**Comment by ravinsp** [comment]
Hi Richard,
Yesterday Ravidu was able to get rid of shared_ptr. He was able to make use of rvalue && and move() instead. As you said we don’t need the data once we release it to the socket (fire and forge). He was making other improvements in that part of the code as well. You can have a look once he issues a PR.

**Comment by codetsunami** [comment]
Great, we do need to consider broadcast messages, but that sounds like a good start

**Comment by codetsunami** [comment]
So by that I mean what if you have to relay the same message to 500 peers. We don't want to deep copy that message 500 times so in that instance a shared_ptr is actually a good idea. (We could use string_view but then we still need to figure out when they've all finished sending it so it can be cleaned up at the appropriate time.)

**Comment by ravinsp** [comment]
Yes. I’ve thought about it. I was thinking going outside of the existing queue in the “session”. Maybe put it into another queue of shared_ptr in each session and adding some extra code for reading and clearing from that queue. 

I wouldn’t like to do synchronization of the multiple async sends. That will be tricky to get right.

**Comment by ravinsp** [comment]
At some point we might have rethink about this entire queue strategy. We are currently using single-threaded async processing for sends and receives. We have look at the current implementation more carefully and maybe transition to multi-threaded processing (with a thread pool) later.

**Comment by codetsunami** [comment]
I was assuming you’d switch to threads later. It’s worth investigating if beast has any internal queuing mechanics. I haven’t looked yet.

**Comment by ravidulashan** [comment]
When we talk about the trailing undescore in member variables of classes in sock namespace. Isn't it the common convention to use a trailing underscore to define a class member?. So far in the project classes have been used only in this sock namespace, that's why member variables have a trailing underscore and other variables of other namespaces don't have it.

**Comment by codetsunami** [comment]
Afaik it's no convention ever recommended by Stroustrup.

Regardless you guys can use any convention you want, but it needs to be consistent over the whole project.

**Comment by nbougalis** [comment]
I think that using move semantics is your best bet for now.

**Comment by ravinsp** [comment]
Thanks @nbougalis. We have refactored places where we pass messages around with move sematics. We can do that with low risk since it's easy to determine lifetime of the message and hand it over to the next piece of logic.
