### ISSUE TITLE
Replace const string& with string_view

### ISSUE THREAD

**Issue by ravinsp** [HotPocketDev/core#23]
@codetsunami kept mentioning string_view a couple of times earlier. We can make great use of string_view due to the nature of the way we use strings and their lifetimes in our project. We currently use `const string&` to pass readonly string reference to function parameters. But since we are using C++17 we can make use of `string_view` which is the recommended drop-in replacement for `const string&` for modern code. We will also be able to make use of `string_view` for reading p2p protocol messages as well to maintain zero-copy nature of protocol parser (#11). @asanka-indrajith @ravidulashan

**Comment by codetsunami** [comment]
Really happy you guys are starting to use all the C++17 features. This will greatly improve the scalability of the project imho.

**Comment by ravinsp** [comment]
Fixed in https://github.com/HotPocketDev/core/commit/56c3e3ee93ddcc54bba099c0beaed411bdc4842c
One omission is `version_compare()` which uses istringstream. Left it out since it's not performance critical code.
