### ISSUE TITLE
pipes and zerocopy pipes

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#24]
### Pipes

These pipes need to be created and destroyed once per contract execution.
https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/usr/usr.cpp#L202

Reason being that parent process needs to close off two ends of the pipes after the fork. So a subsequent fork from the parent now lacks those pipe ends, but the child process needs these.

I'll explain more detail because it can get confusing even for seasoned developers.

There are two half duplex pipes (single direction), we'll call these:
1. parent_to_child
2. child_to_parent

Each of these pipes has a place to write to named "1" and a place to read from named "0".

There are four ends to the set of pipes as follows:
```C++
parent_to_child[0], parent_to_child[1]
child_to_parent[0], child_to_parent[1]
```

When we fork after creating this set of pipes we now have 8 ends. This is because the parent has 4 ends and the child has 4 duplicate ends.

To make communication work correctly we need to close unused ends.
In the parent we need to close the child's reading and writing ends. So we close `parent_to_child[0]` (child's reading end) and `child_to_parent[1]` (child's writing end).

In the child we need to close the parent's reading and writing ends. So we close `parent_to_child[1]` (parent's writing end) and `child_to_parent[0]` (parent's reading end).

Now we have 2 open ends per process, which is 4 ends total which allows correct pipe communication.

Once the child process exits its two remaining ends are closed. The parent is left with two ends: `parent_to_child[1]` which can no longer be written to and `child_to_parent[0]` which can still be read from until all buffered bytes have been read and then EOF occurs.

If we were to fork again in this state the child process would receive these same useless already finished pipe ends and no communication would be possible. So we have to close off these ends and then re-run the pipe syscalls again to set up a new set of pipes for the next execution. Afaik pipe calls are inexpensive so this isn't a big deal.

This needs to be done once for each user for each contract execution and additionally for stdin/stdout as well.

### Zerocopy pipes

What could be a big deal is copying user data into the pipes, especially for example if the user's input is quite large, like for example a 100mib file. Since our users' inputs already exist in our process memory it would be nice if we could just tell the other process's read operation to go ahead and read some of our process memory.

For this I believe we can use the vmsplice syscall. This retains all the semantics of using file descriptors for the contract's user communication operations, which are widely supported across thousands of programming languages, without the overhead of unnecessary additional copies. 

http://man7.org/linux/man-pages/man2/vmsplice.2.html

Incidentally we should also add a cfg option setting maximum user input per round so that contracts which expect large amounts of user input can have them without opening DoS attack surface area for other types of contracts that might only expect say 20 bytes.

**Comment by ravinsp** [comment]
You are right. I do understand pipe read/write sides but it totally slipped my mind that these per-user pipes would be open in the forked process as well! Coupling these with contract execution life cycle also makes more sense. 

I suspect there’s an fd leak in `write_to_stdin` as well although it is inside the parent process only. 
https://github.com/HotPocketDev/core/blob/ebf13209e13f464326bff192314b25d6d1b4fea1/src/proc.cpp#L122

**Comment by codetsunami** [comment]
All good.

An easy way to test if there's a leak is simply run `lsof` against the process as it runs and see if its total FD number is increasing over time.

In case you haven't seen it this is my C code for handling pipes in the prototype. It may be of some use. It's FD leak free in my testing.

https://github.com/codetsunami/posix-pipe-fork-exec/blob/362060203b2eb705fa7acb969bf2ecf9e80ab102/src/posix.cc#L114

**Comment by ravinsp** [comment]
I studied that code of yours in order to come up with my implementation. Thanks. 

In the case of user pipes, can we only only create them if there are consensus-reached pending inputs from the user as an optimization. (Maybe there are contracts which emits events to the user without having input?)

We would need to collect user inputs from socket into a buffer until the contract runs. When there are multiple inputs from the user would this be single “append” buffer or a queue of buffers? In the case of queue of buffers, do we just write them all to input pipe? In that case is it up to the contract to break down individual inputs because everything coming in from the pipe will appear contiguous?

**Comment by codetsunami** [comment]
Every user who has an active connection on the contract's hp network should have a set a pipes for each execution, even if that users hasn't sent any inputs. This is because, as you point out, the contract may wish to send something to that user.

So an example is a secure instant messaging contract. I connect, you connect. I send the contract a message that it relays to you, but you haven't sent anything. The contract needs an FD for your user so it can relay the message to you.

User inputs are collected from the user's socket and then fed into consensus, not directly into the contract. Once consensus has been achieved inputs are fed from a buffer into the contract.

During stage 0 proposals, full user inputs are circulated between peers. Either the node has that user connected directly in which case he already has a buffer containing the user's inputs or the node doesn't have that user connected in which case the buffer will have been populated from a stage 0 proposal from the peer that does have that user connected.

Determining when/where to break a continuous or repetitive stream of input from a user into an input bundle to be proposed is not trivial. I would suggest we provide a default behaviour which is something like "read everything from the socket until either too much time has elapsed, no bytes remain or X bytes have been read" where X is the user input limit, and a second behaviour which can be set in cfg which basically uses a BSTR-like protocol along the lines of <data length><data>, which will help people who need to write contracts that move very large amounts of data and let hotpocket accumulate a user's incoming data until the full <data length> has been received before proposing it as input to consensus.

**Comment by ravinsp** [comment]
Even if Hot Pocket follow `<data length><data>` format, we would have trouble feeding multiple such messages (after reaching consensus of course) into the contract pipe. Then we would need a protocol in place for HP<-->SC pipe as well...

**Comment by codetsunami** [comment]
I think for `<data length><data>` it would be one such packet per consensus round. If the user wants to send another packet they must wait a round. Since the user is telling us how much data they want to send its up to them to figure out what that number actually is before they send it. Call this mode 1.

In the default mode we would do a similar thing but infer `<data length>` based on the amount of data actually sent by the user. Call this mode 0.

If the user sends more data after we "close off" a packet in default mode we can always wait until the next consensus round.

Based on feedback from contract authors there might be more processing modes in the future. E.g. Inputs delimited by a double carriage return (HTTP style) might be useful for command line. This could be mode 2.

Feeding user inputs into the pipe for contract execution should be straight forward. We have the user's input for this round in a contiguous piece of memory and then we use vmslice to map it into the user's FD?

**Comment by ravinsp** [comment]
Awesome! That's clear. For message unit modes I think the most flexible way is to implement a simple mode switching JSON message sent from the user's client. Then they can switch modes as they wish. The mode switch request does not have to involve in consensus because its just between connected user and the node itself. Contract config will specify supported modes.

**Comment by codetsunami** [comment]
I like that. Let the user specify their mode in the handshake. I was seeking to avoid any control messages past the handshake but we might end up with one anyway. It's conceivable the user will want to communicate with the hpcore rather than the contract for some connection or key management purpose.

**Comment by ravinsp** [comment]
Pipe optimizations made in #26 and #28 
Work items added for user input modes and thresholds.
