### ISSUE TITLE
Flatbuffer message schema

### ISSUE THREAD

**Issue by asanka-indrajith** [HotPocketDev/core#27]
This is the new peer-to-peer message schema I've came up with FlatBuffer.

```
//IDL file for p2p message schema.
namespace p2p;

table StringKeyValuePair { 
    key:[ubyte]; 
    value:string; 
 }

 table ByteArray {
     array:[ubyte];
 }

table Container { //root type for message
    version: uint16; 
    signature:[ubyte];
    content:[ubyte]; // message content: byte array of proposal,npl,etc
}

union Messase { Proposal, Npl }

table Content {
    message:Messase;
}

table Proposal {
    pubkey:[ubyte];
    timestamp:uint64;
    stage: int8;
    time:uint64;
    lcl:[ubyte];
    connections: [ByteArray];
    raw_inputs: [StringKeyValuePair]; //stage 0 inputs 
    hash_inputs:[string];  //stage > 0 inputs (hash of satge 0 inputs)
    raw_outputs: [StringKeyValuePair]; //stage 0 outputs 
    hash_outputs:[string];  //stage > 0 outputs (hash of satge 0 outputs)
    state: State;
}

table Npl {
    pubkey:[ubyte];
    timestamp:uint64;
    data:[ubyte];
    lcl:[ubyte];
}

table StateDifference {
    created: [StringKeyValuePair];
    updated: [StringKeyValuePair];
    deleted: [StringKeyValuePair];
}

table State {
    previous: [ubyte];
    current: [ubyte];
    difference: StateDifference;
    patch: [StringKeyValuePair];
}

root_type Container;
```
We'll have to stick with extra content serialization/parsing as flatbuffer 'union' type doesn't provide mechanism to get size of its value(I initially hoped to avoid this using unions). But still more efficient than protobuf with zero-copy, string_view features.

**Comment by codetsunami** [comment]
Good work getting stuck into flatbuffers

```
table Container { //root type for message
    version: uint16; 
    signature:[ubyte];
    content:[ubyte]; // message content: byte array of proposal,npl,etc
}

```

I assume you're encoding the 'content' field as a byte array so you can check the signature on it more easily.

However decoding it with this might be a problem. Can you add new types to a union without breaking clients running the old version?
```
union Messase { Proposal, Npl }

table Content {
    message:Messase;
}
```

Would it be better to specify an Enum which describes each possible content / packet type? Then decode or ignore an incoming packet based on that?

**Comment by asanka-indrajith** [comment]
Yes. Encoding 'content' part is for easy signature verification.

we can add new types to union as long as new types are added to end, as described in [here](https://github.com/google/flatbuffers/issues/4671)

> Unions share a lot of properties with enums, but instead of new names for constants, you use names of tables. You can then declare a union field, which can hold a reference to any of those types, and additionally a field with the suffix _type is generated that holds the corresponding enum value, allowing you to know which type to cast to at runtime.

basically we can read type and do anything based on that.
```
auto union_type = content.message_type();
if (union_type == Message_Proposal) {
//add to proposal list
}
else{
//ignore
}
```

**Comment by codetsunami** [comment]
That sounds fine then

**Comment by ravinsp** [comment]
Updated Proposal message schema during consensus implementation. Replaced 'string' datatype with 'ubyte'. (not merged to master yet)

```
table StringKeyValuePair { //flatbuff equivalent for dictionary/hashmap for <byte>
    key:[ubyte]; 
    value:[ubyte]; 
 }

 table ByteArray { //To represent list of byte arrays
     array:[ubyte];
 }

table Proposal_Message { //Proposal type message schema
    pubkey:[ubyte];
    timestamp:uint64;
    stage: int8;
    time:uint64;
    lcl:[ubyte];
    users: [ByteArray];
    raw_inputs: [StringKeyValuePair];   //stage 0 inputs 
    hash_inputs:[ByteArray];            //stage > 0 inputs (hash of stage 0 inputs)
    raw_outputs: [StringKeyValuePair];  //stage 0 outputs 
    hash_outputs:[ByteArray];           //stage > 0 outputs (hash of stage 0 outputs)
    state: State;
}

```
