### ISSUE TITLE
HP User signing keys

### ISSUE THREAD

**Issue by ravinsp** [HotPocketDev/core#30]
How do we ensure user's signing keys are generated using the same algorithm used in Hot Pocket (libsodium)? Is it just a matter of documenting in our specification?

Since the user public key is passed into the contract (which will probably use it for user data authentication), the smart contract would also have to agree on this.

**Comment by codetsunami** [comment]
Suggest prepending a byte to the public key when it is transmitted that specifies the key type. 00 for our current default ed25519. And if we add another keytype later we can allocate 01 for that. Shouldn't inhibit verification, simply pass the same key buffer but +1 on the pointer to libsodium.

So it'd be like
```
<key type byte>< ... public key bytes>
```

**Comment by codetsunami** [comment]
And then pass that same format to the contract binary as the user's public key, and the contract can do the same operation on it if it needs to verify a signature.

**Comment by ravinsp** [comment]
Couple of problems:
It's the user who would send us the public key in the "challenge_response" message which is JSON. Requiring another lesser-known convention of prefix-byte when constructing the base64 pub key would be confusing for the user client program. In that case it's better to have a json field "keytype" in the JSON message.
Same goes for the contract input which is JSON. We can introduce 'keytype' field into the contract input JSON as well.

Since you seemed to be talking about binary-based messages, should be abandone JSON in the above cases? I assume we use JSON in those cases for better interoperability and adoption.

**Comment by codetsunami** [comment]
That's true I forgot you're using base64. I always preferred hex encoding for EC keys for exactly this reason.

For example ECDSA relies on prefixing to determine key compression even vs odd. E.g. prefix of 0x02 for even, 0x03 for odd or 0x04 for uncompressed. So in a sense this is a standard way to do it.

Introducing another field to describe the key type is also possible. We could do this and then just default to ed25519 if it's not specified (make it optional).

**Comment by codetsunami** [comment]
Why don't we introduce the prefixing for when the key is circulated in consensus and passed to the smart contract but use two fields (one being optional) on the user interface side of things? This will make it easy for contract developers to know which signing algorithm they need to look at (if any)

**Comment by codetsunami** [comment]
(I'd like to keep JSON for user messages)

**Comment by ravinsp** [comment]
What about contract input? We should follow same 'keytype' optional field for contract input json as well (unless you want that to happen via a binary protocol).

**Comment by codetsunami** [comment]
I'd like to keep the fdlist json if possible.

Is there some significant downside to using hex keys instead of base64 keys? Just curious why this choice was made?

**Comment by ravinsp** [comment]
I chose base64 due to reduced length than hex. I was thinking if we are transferring a lot of those around even few bytes would matter.

**Comment by ravinsp** [comment]
WIth base64 also we can include that extra prefix byte, it's just that it's no human decodable. You would have to first decode base64 into binary and then read the prefix byte.

**Comment by ravinsp** [comment]
That "few bytes" saving I was hoping would be offset by the "keytype" extra field though. :-) Then again, it's optional.

**Comment by codetsunami** [comment]
Public keys are transferred as binary in the p2p protocol and as an encoded form just once when the user connects. It's also transferred to the SC when it is executed but this can be a zero copy op.

I think tbh hex will be easier for users and programmers. Most keys are moved around in hex for most projects.

My concern with adding another field on the SC fdlist is that the pubkey of the user is the user's identifier. Adding key type as a subfield would work but it adds a lot of unnecessary overhead.

Rippled uses the prefix 0xED for ed25519 curve keys and 0x02 and 0x03 for secp256k1 keys. I would just follow their lead.

**Comment by ravinsp** [comment]
Yes, we are currently using base64 only in the places you mentioned and the contract config (which is one-off thing). Yes it looks to me that my original aim doesn't add that much value now. Specially with vmsplice.
"pubkey of the user is the user's identifier" that is a strong argument. Yep, hex would unify things. It's better if we can stuff extra pieces easily discernible information in the identity itself.
I will switch to hex. Thanks.

**Comment by ravinsp** [comment]
Fixed in 0fb9ebf7
