### ISSUE TITLE
JSON for SC -> HP instructions

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#31]
At the moment when a contract is executed HP sends the json `fdlist` to the SC. However this communication is one way. It is conceivable that the SC might want to send back some instructions to HP. So for example, after processing inputs from users the SC might decide it wants to update its UNL, or some other parameters.

In the prototype anything written to stdout by the smart contract is simply discarded. We _could_ use stdout of the SC to supply instructions to HP. However this makes contracts harder to write and debug, as contract developers want to be able to log events in their contract easily. Therefore I recommend we actually pass stdout straight from the SC to HP's logging mechanism for easy debugging.

Instead I think we should provide a HP control FD in the `fdlist` which allows the SC to emit a control instruction to HP. As above an example control instruction would be to remove or add a node from the UNL. Another might be to abandon or block a particular user who is misbehaving at the application layer.

These control instructions actually need to pass consensus. An easy way to do this is simply take any control instructions written by the SC and place them on a special key in the outputs map. The consensus algorithm runs as normal and then when processing canonical outputs at stage 3 that key is processed by a special function that applies the control instructions to each node.

**Comment by ravinsp** [comment]
Good idea. How about we also introduce a control-reply fd as well? It would be a pair of fds just like user i/o fd pair.

We’ll name them hpin and hpout from the viewpoint of SC. Hpout is the fd you talked about. Hpin would be used for sending control replies (or events) from HP back into SC. Similar to user outputs (generated by SC), hpin messages from round N would be subjected to consensus and passed to SC in round N+1.

**Comment by codetsunami** [comment]
Good idea. Naming should be from the perspective of the smart contract however. So for the SC developer hpin would be the reading pipe and hpout would be the writing pipe.

Also we shouldn't force SC developers to read from hpin. This is an optional feature, they can use it if they want to. HP shouldn't expect any special defined behaviour if it provides some instruction to the SC on hpin, but the SC can expect well defined behaviour when providing instructions to HP on hpout.

E.g. all HP->SC data on this pipe is informational for the SC's benefit. I imagine it would typically consist of success or failure messages from a previously issued control instruction

**Comment by ravinsp** [comment]
Implemented in #32. JSON based control protocol has to be implemented on top of it in the future.
