### ISSUE TITLE
boost::beast TLS

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#35]
We need to support HTTPS (TLS) websockets. We want to ensure users can privately communicate with nodes.

There are SSL examples here https://github.com/boostorg/beast/tree/develop/example/websocket/server

I think for the convenience of contract developers we should natively support TLS 1.3 handshaking using the same key already specified in the contract config. TLS 1.3 contains support for ed25519 keys. These certs would display as self-signed if a browser navigates to them.

We should also allow them to specify their own TLS certificate if they choose to. This would be an advanced feature.

**Comment by ravinsp** [comment]
Specifying own TLS cert implemented in #41 
TLS1.3 ed25519 support tracked under internal tracker:75433.
