### ISSUE TITLE
The two billing systems: corebill, appbill

### ISSUE THREAD

**Issue by codetsunami** [HotPocketDev/core#47]
There's been some discussion if necessary billing systems here https://github.com/HotPocketDev/core/issues/39 and https://github.com/HotPocketDev/core/issues/33
Here is a comprehensive billing concept for the whole project.

There are two billing systems:
**1. CoreBill**
This is the system mentioned in https://github.com/HotPocketDev/core/issues/39 and is a per-node internal ledger tracking the protocol-level behaviour of peers. If a peer (including a user) is behaving badly at the HP protocol layer, or any protocol under that layer, the node currently tolerating that bad behaviour will privately tally demerits against that peer until the peer is disconnected and a cooldown is instituted to prevent repeat connections. This billing should be indexed by IP, not by public key. For the sake of simplicity this billing system is not subject to consensus and information about bad peers is not transmitted between nodes (as this potentially opens up further DDoS attack surface area).

CoreBill should have some settings in the contract config e.g.: _aggressive, moderate, light, off._ Off would be used for debugging.

**2. AppBill**
This is an application layer billing system that controls end user misbehaviour according to the contract's own concept of what constitutes user misbehaviour. This is analogous to a transaction fee attached to a Bitcoin or XRP ledger transaction. 

To keep this system as general and simple as possible, I propose first making some changes to the way user inputs are passed by hpclient:

Each user input should be packaged on the client side into a signed packet, signed with the user's public key. This will allow non-UNL peers to pass user connections and messages into the network without requiring UNL peers to trust them. This also eliminates a lot of complexity around knowing when to 'cut off' user inputs. It is up to the connecting client to manage this. Ed25519 has very fast signing https://ed25519.cr.yp.to/ so this isn't expected to produce much impact on client side, even on very light clients like mobile phones.

Now that we know a particular packet of input is definitely from a particular user we can bill that user according to their public key. The most general way to do this is to leave it to the contract to operate a billing ledger as part of the contract. When it receives messages on a user's fd it bills the user in its own database accordingly and this database lives in the /state/ folder and is subject to consensus.

This still leaves open the attack vector of users generating large numbers of new public keys, and/or dumping large amounts of input into the network. To prevent that I suggest we have another predefined execution mode for contract binaries, similar to the user-read-mode https://github.com/HotPocketDev/core/issues/34 but instead the proposed user connections and inputs are passed as json and the contract returns json on stdout indicating which of these are *probably OK to place into consensus* and which users should be blocked. If hpcore receives a block on a user at AppBill it should translate that into an appropriate CoreBill penalty.

**3. XRPLBill**
However all of this is rather involved for contract developers so in addition to the above I propose writing a default AppBill behaviour which does not require contract developers to implement the above special mode or a bespoke billing system in their contract. In this default AppBill mode we will do all the hard work for the contract developer: each hpcore instance would participate as a light-weight peer connected to the XRP ledger, watching a contract-specific XRP ledger address (specified in the contract config). If a user wishes to connect to the contract they first send some tokens to this address from an XRP address they own. They then use the public key associated with their XRPL address as their user public key for connecting to and interacting with the contract.

The default billing scheme would be based on a cost per byte figure specified in the contract configuration. So for example 10 drops per byte. This byte count would include all bytes 'owned' by the user inside the consensus rounds. So their bytes in the connection field, their bytes in the input field, but not bytes sent back by the contract.

In this mode hpcore would mimic the behaviour of a well designed contract specified in 2. It would keep a simple flat file sorted list of public keys and their 'credit' balances in the contract's /state/ folder under a preset filename say /state/.xrplbill which would be subject to consensus rounds. It would imitate the special execution mode from 2 but instead of running the contract binary it would run a function that checks the .xrplbill file and determines if a user's connection/inputs can be serviced. It would monitor the xrpl for transactions which would credit a user and queue these for recording in .xrplbill. The queue would be written out before the check function runs.

This mode has the advantage of preventing sybil attacks, as you need to create a new XRPL account for each public key you connect to a hp contract with. With 20 XRP reserve this quickly becomes cost prohibitive.

I'm already most of the way through programming an example XRPL light node, which would be essential to make this mode work. Since this mode is a special case of 2, it would be sufficient to program 2 until the lite XRPL node is complete.

**Complexity**
Preventing spam and preventing attack surface area is non-trivial. Preventing complexity in the billing system is also non-trivial. Ideally we want a good billing system that doesn't need much thinking about. It just works, in the way people expect, but has good features available for those developers that want them.

**Comment by ravinsp** [comment]
Did some thinking on user I/O re-architecture to support user input submissions by trust-less peers.

I suggest we implement user I/O as a 'stack' of protocols. The bottom layer will be the core user I/O which is equivalent to what we have right now (and also in HP prototype). In this layer, we will not interpret user inputs/outputs. We just blindly transmit them via proposals as raw inputs and hashes and achieve consensus. The core user I/O has the assumption that all inputs are trusted and the per-user input/output ordering will be decided by the hashes. To support extension, this layer will have a hook to integrate custom hashing function and custom validator function.

Contract can specify whether it needs to be invoked for custom hashing and validation for inputs/outputs. This can be specified as `iointerception: custom` in config file. It can specify `iointerception: hp-trustless` to invoke HP built-in interception provider. In the future this may become a plugin system for I/O handling with several I/O interception providers. `iointerception: off` will mean no additional processing is done other than what core I/O layer does.

We will implement trust-less I/O provider to do exactly what is mentioned above. To provide signature verification support and sequence no. etc...

This is similar to the case where AppBill layer is implemented on top of CoreBill layer. I think a layered approach for user I/O will make it easier to handle the chunks of development work and allows for introducing convenient built-in features on the go without committing to everything beforehand. It will also help keep consensus protocol simple.

**Comment by codetsunami** [comment]
I think for simplicity we should make all user inputs signed, and those inputs circulated throughout the network independently of stage 0 proposals. The inclusion of user inputs into a ledger is done by the UNL peers via proposals. When consensus is reached the input is committed to a ledger and removed from the circulating / pending inputs. A user input should specify a max-ledger or other expiry mechanism to ensure its inclusion or non-inclusion into a ledger is definitive and not left hanging.

In otherwords turn user inputs into transactions as they exist in bitcoin and xrpl.

**Comment by ravinsp** [comment]
Basic corebill tracking implemented in https://github.com/HotPocketDev/core/commit/7815390b255e6c24cb8dc83aae786a9f5adc5d2e

**Comment by codetsunami** [comment]
This should be included in documentation somewhere but it's no longer needed in the issues list
