### ISSUE TITLE
consensus ledger format

### ISSUE THREAD

**Issue by asanka-indrajith** [HotPocketDev/core#49]
We are going to use Flatbuffer to create ledger records using following schema.

```
table Ledger {
    time:uint64;
    lcl:[ubyte];
    users: [ByteArray];
    inputs: [RawInputList]; 
    outputs: [ByteArray];
}

table RawInputList {
    pubkey:[ubyte];
    inputs:[ByteArray];
}

root_type Ledger;
```
*state is omitted from ledger for now since we haven't implemented state management yet.

Also I have concerns regarding ledger saving and retrieval logic. We are relying on file system to retrieve last closed ledger based on modified time. I think better approach would be to prepend timestamp to ledger name and use it retrieve lcl.

**Comment by codetsunami** [comment]
Flatbuffer for saved ledgers is fine.

As discussed yesterday with Ravin ledgers should have a ledger sequence number in them. The genesis ledger of a HP network will be led_seq_no = 0, and each closed consensus ledger thereafter increments the sequence counter.

The sequence number can be used as the filename, this will make it easy to discover which are missing from the sequence.

**Comment by ravinsp** [comment]
OK That's good. Slightly off topic; we would also need a user control message to retrieve the current seq_no from the node right? User needs this to include TTL in input message.

**Comment by codetsunami** [comment]
Yes I think a ping-pong message between a node and user client is a good idea, that should include a last ledger seq number as part of the reply message when the node is replying, and doubles as a way to see if the connection is alive.

The same message type could also be passed routinely between connected peers, especially non-UNL peers connected to UNL peers.

It could also include some connection specific suppression flags like 'don't send me any proposals'. A UNL peer would pass this flag on a ping or pong message to a non-UNL peer for example, to avoid wasting bandwidth.
